version: "3.8"

services:
  api:
    image: node:14
    container_name: taktics-api
    working_dir: /app
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install --legacy-peer-deps && npm start"

  admin:
    image: node:14
    container_name: taktics-admin
    working_dir: /app
    volumes:
      - ./admin:/app
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npm install --legacy-peer-deps && npm start"


